In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib


In [2]:
height= np.round(np.random.normal(1.75, 0.20, 7000), 2)
weight= np.round(np.random.normal(60.32, 15, 7000), 2)
population=np.column_stack((height, weight))

In [4]:
print('height:\n',height)
print('weight:\n',weight)
print('population:\n',population)

height:
 [1.68 1.44 1.53 ... 1.74 2.   1.57]
weight:
 [71.85 93.56 61.18 ... 59.84 52.1  81.48]
population:
 [[ 1.68 71.85]
 [ 1.44 93.56]
 [ 1.53 61.18]
 ...
 [ 1.74 59.84]
 [ 2.   52.1 ]
 [ 1.57 81.48]]


In [5]:
print(height.ndim)

1


In [6]:
print(weight.ndim)

1


In [7]:
print(population.ndim)

2


In [8]:
print(height.shape)

(7000,)


In [9]:
print(weight.shape)

(7000,)


In [11]:
print(population.shape)

(7000, 2)


In [12]:
print(np.size(height))

7000


In [13]:
print(np.size(weight))

7000


In [14]:
print(np.size(population))

14000


In [15]:
print(height.itemsize)

8


In [16]:
print(weight.itemsize)

8


In [17]:
print(population.itemsize)

8


In [21]:
print(height.min())
print(weight.min())
print(population.min())

1.09
9.4
1.09


In [22]:
print(height.max())
print(weight.max())
print(population.max())

2.48
114.12
114.12


In [23]:
print(height.mean())
print(weight.mean())
print(population.mean())

1.7504
60.388532857142856
31.06946642857143


In [24]:
print(height.std())
print(weight.std())
print(population.std())

0.20001802775892835
14.942452240094054
31.16514237609776


In [25]:
print(height.sum())
print(weight.sum())
print(population.sum())

12252.8
422719.73
434972.53


In [26]:
help(plt.hist)

Help on function hist in module matplotlib.pyplot:

hist(x, bins=None, range=None, density=None, weights=None, cumulative=False, bottom=None, histtype='bar', align='mid', orientation='vertical', rwidth=None, log=False, color=None, label=None, stacked=False, normed=None, *, data=None, **kwargs)
    Plot a histogram.
    
    Compute and draw the histogram of *x*.  The return value is a tuple
    (*n*, *bins*, *patches*) or ([*n0*, *n1*, ...], *bins*, [*patches0*,
    *patches1*,...]) if the input contains multiple data.  See the
    documentation of the *weights* parameter to draw a histogram of
    already-binned data.
    
    Multiple data can be provided via *x* as a list of datasets
    of potentially different length ([*x0*, *x1*, ...]), or as
    a 2-D ndarray in which each column is a dataset.  Note that
    the ndarray form is transposed relative to the list form.
    
    Masked arrays are not supported at present.
    
    Parameters
    ----------
    x : (n,) array or seque