In [1]:
import numpy as np

In [2]:
a = [-12, 16]
b = [12, 9]

In [3]:
#dot product
print(np.dot(a,b))

0


In [4]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])


In [6]:
#cross product
print(np.cross(x,y))

[[-3  6 -3]
 [ 3 -6  3]]


In [9]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [11]:
#element wise multiplication
print(a*b)

[[ 5 12]
 [21 32]]


In [15]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

In [16]:
# element wise addition
print(np.add(X,Y))

[[17 15  4]
 [10 12  9]
 [11 13 18]]


In [22]:
# using loops
for i in range(len(X)):
    for j in range(len(X[i])):
        result[i][j]= X[i][j]+Y[i][j]
print(result)
    

[[17, 15, 4], [10, 12, 9], [11, 13, 18]]


In [23]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]


In [25]:
#matrix multiplication
for i in range(len(X)):
    for j in range(len(Y[i])):
        for k in range(len(Y)):
            result[i][j]+=X[i][k]*Y[k][j]
print(result)
#print(np.dot(X,Y))
        

[[228, 320, 120, 54], [148, 194, 146, 28], [238, 314, 224, 46]]


In [26]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

In [27]:
#determinant
det = np.linalg.det(matrix)
print(det)

17.999999999999996


In [28]:
#inverse
inv = np.linalg.inv(matrix)
print(inv)

[[-0.05555556  0.11111111  0.5       ]
 [ 0.27777778  0.44444444  0.5       ]
 [-0.11111111  0.22222222  0.        ]]


In [29]:
a = np.array([[1., 2.], [3., 4.]])

In [30]:
inv = np.linalg.inv(a)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]
