In [2]:
#scalar product of vectors
import numpy as np
a =np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [3]:
#cross product
print(np.cross(a,b))

[-4 -4]


In [4]:
#entrywise product
print(a*b)

[[ 5 12]
 [21 32]]


In [5]:
#matrix addition
print(np.add(a,b))

[[ 6  8]
 [10 12]]


In [6]:
#matrix multiplication
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [8]:
#determinant of matrix
print(str(int(np.linalg.det(a))))

-2


In [10]:
#inverse of matrix
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]
